version: "3.9"

services:
  backend:
    build: ./backend
    container_name: doctorscribe-backend
    env_file:
      - .env
    restart: unless-stopped
    expose:
      - "3000"

  nginx:
    build:
      context: ./frontend
      args:
        - VITE_AWS_PRESIGN_S3_URL=${VITE_AWS_PRESIGN_S3_URL}
        - VITE_API_GATEWAY_BASE_URL=${VITE_API_GATEWAY_BASE_URL}
    container_name: doctorscribe-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"